# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.10.8753.32995'
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)\project.json'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      # Read the JSON file
      
      $jsonContent = Get-Content -Path '$(Build.SourcesDirectory)\project.json' -Raw
      
       
      
      # Convert JSON content to PowerShell object
      
      $jsonObject = $jsonContent | ConvertFrom-Json
      
       
      
      # Access the value of a specific attribute
      
      ${env:ENTRYPOINT_VALUE} = $jsonObject.main
      
       
      
      # Output the value
      
      Write-Host "Value of attribute_name is: ${env:ENTRYPOINT_VALUE}"
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath_Orch'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Test'
    entryPoints: '$(ENTRYPOINT_VALUE)'